name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: [ windows-latest ]

    steps:
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup VS environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Generate projects
      run: |
        mkdir _build
        cd _build
        cmake -G Ninja `
          -DCMAKE_BUILD_TYPE=RelWithDebInfo `
          -DCMAKE_CXX_COMPILER=cl `
          -DCMAKE_C_COMPILER=cl `
          ..

    - name: Build
      run: |
        cmake --build _build

    - name: Copy resource tool artifacts
      run: |
        cd _build
        mkdir _resource-tool
        Copy-Item Tools/ResourceTool/ResourceTool.dll -Destination _resource-tool/
        Copy-Item Tools/ResourceTool/ResourceTool.pdb -Destination _resource-tool/
        Copy-Item Libraries/ResourceLib/ResourceLib_HM2.dll -Destination _resource-tool/
        Copy-Item Libraries/ResourceLib/ResourceLib_HM2.pdb -Destination _resource-tool/
        Copy-Item Libraries/ResourceLib/ResourceLib_HM3.dll -Destination _resource-tool/
        Copy-Item Libraries/ResourceLib/ResourceLib_HM3.pdb -Destination _resource-tool/
        Copy-Item ../LICENSE -Destination _resource-tool/

    - name: Copy codegen tool artifacts
      run: |
        cd _build
        mkdir _codegen
        Copy-Item Tools/CodeGen/CodeGen.exe -Destination _codegen/
        Copy-Item Tools/CodeGen/CodeGen.pdb -Destination _codegen/
        Copy-Item Libraries/CodeGenLib/CodeGenLib.dll -Destination _codegen/
        Copy-Item Libraries/CodeGenLib/CodeGenLib.pdb -Destination _codegen/
        Copy-Item ../LICENSE -Destination _codegen/

    - name: Archive resource tool
      uses: actions/upload-artifact@v2
      with:
        name: resource-tool
        path: |
          _build/_resource-tool/*

    - name: Archive codegen tool
      uses: actions/upload-artifact@v2
      with:
        name: codegen
        path: |
          _build/_codegen/*

  create_release:
    name: Create release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}

    steps:
    - name: Create release
      id: create
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: startsWith(github.ref, 'refs/tags/v0.')

  upload_release:
    name: Upload release artifacts
    needs: create_release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        artifact: [ resource-tool, codegen ]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.artifact }}

    - name: Archive artifact files
      run: |
        cd ${{ matrix.artifact }}
        zip -r ${{ matrix.artifact }}.zip *

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ${{ matrix.artifact }}/${{ matrix.artifact }}.zip
        asset_name: ${{ matrix.artifact }}.zip
        asset_content_type: application/zip